// versions.gradle.kts
val androidGradlePlugin = "8.4.0"
val androidTools = "31.4.1"
val kotlin = "2.0.0"
val ksp = "2.0.0-1.0.21"
val room = "2.6.1"
val firebaseCrashlyticsPlugin = "2.9.9"
val firebasePerfPlugin = "1.4.2"
val googleOss = "17.0.0"

extra["androidGradlePlugin"] = "com.android.tools.build:gradle:$androidGradlePlugin"
extra["androidToolsCommon"] = "com.android.tools:common:$androidTools"
extra["composeGradlePlugin"] = "org.jetbrains.kotlin:compose-gradle-plugin:$kotlin"
extra["firebaseCrashlyticsPlugin"] = "com.google.firebase:firebase-crashlytics-gradle:$firebaseCrashlyticsPlugin"
extra["firebasePerformancePlugin"] = "com.google.firebase:perf-plugin:$firebasePerfPlugin"
extra["kotlinGradlePlugin"] = "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin"
extra["kspGradlePlugin"] = "com.google.devtools.ksp:com.google.devtools.ksp.gradle.plugin:$ksp"
extra["roomGradlePlugin"] = "androidx.room:room-compiler:$room"
extra["googleOssLicensesPlugin"] = "com.google.android.gms:oss-licenses-plugin:$googleOss"